/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionempresas;

import javax.swing.JTable;
import Logica.consulta;
/**
 *
 * @author FAMILIA
 */
public class Consultar_Empresas extends javax.swing.JFrame {

    /**
     * Creates new form Consultar_Empresas
     */
    public Consultar_Empresas() {
        initComponents();
        setLocationRelativeTo(null);
        tabla_consulta.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_consulta = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("CONSULTAR");
        setMinimumSize(new java.awt.Dimension(1067, 504));
        setResizable(false);

        jPanel1.setLayout(null);

        tabla_consulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "RUC", "RAZON SOCIAL", "ACTIVIDAD PRINCIPAL", "SECTOR", "PROVINCIA", "CIUDAD", "DIRECCION", "TELEFONO", "E-MAIL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_consulta.setCellSelectionEnabled(true);
        tabla_consulta.setMinimumSize(new java.awt.Dimension(1240, 685));
        tabla_consulta.setPreferredSize(new java.awt.Dimension(1240, 685));
        tabla_consulta.setRowHeight(20);
        tabla_consulta.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabla_consulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_consultaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_consulta);
        tabla_consulta.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (tabla_consulta.getColumnModel().getColumnCount() > 0) {
            tabla_consulta.getColumnModel().getColumn(0).setMinWidth(100);
            tabla_consulta.getColumnModel().getColumn(0).setPreferredWidth(100);
            tabla_consulta.getColumnModel().getColumn(0).setMaxWidth(100);
            tabla_consulta.getColumnModel().getColumn(1).setMinWidth(400);
            tabla_consulta.getColumnModel().getColumn(1).setPreferredWidth(400);
            tabla_consulta.getColumnModel().getColumn(1).setMaxWidth(400);
            tabla_consulta.getColumnModel().getColumn(2).setMinWidth(400);
            tabla_consulta.getColumnModel().getColumn(2).setPreferredWidth(400);
            tabla_consulta.getColumnModel().getColumn(2).setMaxWidth(400);
            tabla_consulta.getColumnModel().getColumn(3).setMinWidth(100);
            tabla_consulta.getColumnModel().getColumn(3).setPreferredWidth(100);
            tabla_consulta.getColumnModel().getColumn(3).setMaxWidth(100);
            tabla_consulta.getColumnModel().getColumn(4).setMinWidth(150);
            tabla_consulta.getColumnModel().getColumn(4).setPreferredWidth(150);
            tabla_consulta.getColumnModel().getColumn(4).setMaxWidth(150);
            tabla_consulta.getColumnModel().getColumn(5).setMinWidth(150);
            tabla_consulta.getColumnModel().getColumn(5).setPreferredWidth(150);
            tabla_consulta.getColumnModel().getColumn(5).setMaxWidth(150);
            tabla_consulta.getColumnModel().getColumn(6).setMinWidth(400);
            tabla_consulta.getColumnModel().getColumn(6).setPreferredWidth(400);
            tabla_consulta.getColumnModel().getColumn(6).setMaxWidth(400);
            tabla_consulta.getColumnModel().getColumn(7).setMinWidth(100);
            tabla_consulta.getColumnModel().getColumn(7).setPreferredWidth(100);
            tabla_consulta.getColumnModel().getColumn(7).setMaxWidth(100);
            tabla_consulta.getColumnModel().getColumn(8).setMinWidth(250);
            tabla_consulta.getColumnModel().getColumn(8).setPreferredWidth(250);
            tabla_consulta.getColumnModel().getColumn(8).setMaxWidth(250);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 20, 1030, 410);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionempresas/Inicio.jpg"))); // NOI18N
        jButton3.setToolTipText("");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(1000, 440, 50, 50);

        jButton1.setText("Cargar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(833, 470, 120, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1067, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabla_consultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_consultaMouseClicked
       // primero, obtengo la fila seleccionada
        //int fila = this.jTableDatos.getSelectedRow();
        // luego, obtengo la columna seleccionada
        //int columna = this.jTableDatos.getSelectedColumn();
        // por ultimo, obtengo el valor de la celda
        //String dato = String.valueOf(this.jTableDatos.getValueAt(fila,columna));
        // ahora envio los datos a buscar en la bd 
        //new Muestra_Consulta().setVisible(true);
        // llamo al metodo en la ventana mostrarCelda encargado de mostrar los datos
        //mostrarCelda.mostrar(fila,columna,dato);
        // hago visible la ventana
       // mostrarCelda.setVisible(true);
    }//GEN-LAST:event_tabla_consultaMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        new Gestion_Crear().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3MouseClicked
  consulta con = new consulta();   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                   
         this.tabla_consulta.setModel(con.buscar_mostrarTabla()); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.tabla_consulta.setModel(con.buscar_mostrarTabla()); 
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultar_Empresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultar_Empresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultar_Empresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultar_Empresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultar_Empresas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_consulta;
    // End of variables declaration//GEN-END:variables
}
